version: '3.8'

services:
  neo4j:
    image: studentwhs/neo4j:5.3.0
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_connector_bolt_advertised__address=:7689
      - NEO4J_dbms_connector_bolt_listen__address=:7689
    ports:
      - "7689:7689"
      - "7474:7474"
    volumes:
      - neo4j_data:/data
    networks:
      - neo4j_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7474 || wget -q -O- http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 10

  backend:
    image: studentwhs/rescuecommandcenter-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7689
      - SPRING_NEO4J_USERNAME=neo4j
      - SPRING_NEO4J_PASSWORD=password123
    ports:
      - "9191:9191"
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - neo4j_network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9191/api/v1/rescuecommandcenter/swagger-ui/index.html || wget -q -O- http://localhost:9191/api/v1/rescuecommandcenter/swagger-ui/index.html" ]
      interval: 30s
      timeout: 10s
      retries: 10

  frontend:
    image: studentwhs/rescuecommandcenter-frontend:latest
    build:
      context: ../../vue-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ../../vue-frontend:/app
      - /app/node_modules
    command: [ "npm", "run", "dev:docker", "--", "--host" ]
    environment:
      NODE_ENV: development

volumes:
  neo4j_data:

networks:
  neo4j_network:
    driver: bridge