name: GitGuardian Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gitguardian-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download GitGuardian CLI installation script
      run: curl -sSL -o ggshield_install.sh https://api.gitguardian.com/ggshield/install

    - name: Verify and run GitGuardian CLI installation script
      run: bash ggshield_install.sh

    - name: Run GitGuardian scan
      env:
        GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      run: ggshield scan repo .